project_name: shepherd

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: shepherd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: frontendtony
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/frontendtony/shepherd"
    description: "A TUI process orchestrator for development environments"
    license: "MIT"
    install: |
      bin.install "shepherd"
    test: |
      system "#{bin}/shepherd", "--help"
